name       : piper
version    : 0.2.902
release    : 10
source     :
    - https://github.com/libratbag/piper/archive/0.2.902.tar.gz : 7b98f7c0159ca09ab6d79e3a0f8dac171df55e50c5ef84fe6c0222095a79f27e
license    : GPL-2.0-or-later
component  : system.utils
summary    :
    - GTK application to configure gaming mice.
    - modaliases : These files are used by the Software Center for hardware detection.
description: |
    GTK application to configure gaming mice.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(liblur)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - python-gobject  # Our mkmodaliases script is lazy and uses gobject.
    - libratbag       # Produce modaliases from the libratbag data
rundeps    :
    - libratbag
    - python3-gobject
    - python-evdev
    - python-lxml
patterns   :
    - modaliases : /usr/share/linux-driver-management/modaliases
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    $pkgfiles/mkmodaliases.py

    # Let LDM know about our aliases
    install -D -m 00644 piper.modaliases $installdir/usr/share/linux-driver-management/modaliases/piper.modaliases
