name       : piper
version    : 0.2.900
release    : 1
source     :
    - git|https://github.com/libratbag/piper.git : 0.2.900
license    : GPL-2.0
component  : system.utils
summary    : GTK application to configure gaming mice.
description: |
    GTK application to configure gaming mice.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(liblur)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
rundeps    :
    - libratbag
    - python3-gobject
    - python-evdev
    - python-lxml
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
