name       : piper
version    : '0.3'
release    : 13
source     :
    - https://github.com/libratbag/piper/archive/0.3.tar.gz : c7210c058de6a6803db462754386785cf5b9ab36dd9e69de6b7a3ca583451401
license    : GPL-2.0-or-later
component  : system.utils
summary    :
    - GTK application to configure gaming mice.
    - modaliases : These files are used by the Software Center for hardware detection.
description: |
    GTK application to configure gaming mice.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(liblur)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - python-gobject  # Our mkmodaliases script is lazy and uses gobject.
    - libratbag       # Produce modaliases from the libratbag data
rundeps    :
    - libratbag
    - python3-gobject
    - python-evdev
    - python-lxml
patterns   :
    - modaliases : /usr/share/linux-driver-management/modaliases
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    $pkgfiles/mkmodaliases.py

    # Let LDM know about our aliases
    install -Dm00644 piper.modaliases $installdir/usr/share/linux-driver-management/modaliases/piper.modaliases
