name       : piper
version    : '0.6'
release    : 24
source     :
    - https://github.com/libratbag/piper/archive/refs/tags/0.6.tar.gz : aa2fb9b63cd926067bdf2842013169e279fe2a159e8575f392fc1f042cdec001
homepage   : https://github.com/libratbag/piper
license    : GPL-2.0-or-later
component  :
    - system.utils
    - modaliases : kernel.drivers
summary    :
    - GTK application to configure gaming mice
    - modaliases : These files are used by the Software Center for hardware detection
description: |
    Piper is a GTK+ application to configure gaming mice. It is a graphical frontent to the ratbagd DBUS daemon which provides the actual configuration support for the devices.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(liblur) # Produce modaliases from the libratbag data
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - flake8
    - python-evdev
    - python-gobject  # Our mkmodaliases script is lazy and uses gobject.
    - python-lxml
rundeps    :
    - libratbag
    - python-evdev
    - python-gobject
    - python-lxml
patterns   :
    - modaliases : /usr/share/linux-driver-management/modaliases
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    $pkgfiles/mkmodaliases.py

    # Let LDM know about our aliases
    install -Dm00644 piper.modaliases $installdir/usr/share/linux-driver-management/modaliases/piper.modaliases
