name       : piper
version    : '0.5.1'
release    : 21
source     :
    - git|https://github.com/libratbag/piper.git : e117e870994c3656bfbde38ccfe5e47ca443ca26
license    : GPL-2.0-or-later
component  : system.utils
summary    :
    - GTK application to configure gaming mice.
    - modaliases : These files are used by the Software Center for hardware detection.
description: |
    GTK application to configure gaming mice.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(liblur)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - flake8
    - python-evdev
    - python-gobject  # Our mkmodaliases script is lazy and uses gobject.
    - python-lxml
    - libratbag       # Produce modaliases from the libratbag data
rundeps    :
    - libratbag
    - python3-cairo
    - python-evdev
    - python-gobject
    - python-lxml
patterns   :
    - modaliases : /usr/share/linux-driver-management/modaliases
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    $pkgfiles/mkmodaliases.py

    # Let LDM know about our aliases
    install -Dm00644 piper.modaliases $installdir/usr/share/linux-driver-management/modaliases/piper.modaliases
