name       : piper
version    : 0.2.905
release    : 12
source     :
    - https://github.com/libratbag/piper/archive/0.2.905.tar.gz : 25e5b3085f386284ce9828afaed4174988d8418c2c626ca3949f79c4f6079a9d
license    : GPL-2.0-or-later
component  : system.utils
summary    :
    - GTK application to configure gaming mice.
    - modaliases : These files are used by the Software Center for hardware detection.
description: |
    GTK application to configure gaming mice.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(liblur)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - python-gobject  # Our mkmodaliases script is lazy and uses gobject.
    - libratbag       # Produce modaliases from the libratbag data
rundeps    :
    - libratbag
    - python3-gobject
    - python-evdev
    - python-lxml
patterns   :
    - modaliases : /usr/share/linux-driver-management/modaliases
setup      : |
    %patch -p1 < $pkgfiles/Add-missing-device-id-for-MX-Master.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    $pkgfiles/mkmodaliases.py

    # Let LDM know about our aliases
    install -Dm00644 piper.modaliases $installdir/usr/share/linux-driver-management/modaliases/piper.modaliases
