name       : piper
version    : 0.2.900
release    : 3
source     :
    - git|https://github.com/libratbag/piper.git : be0aff095dd11697b033cec07339ceaea9c18ce0
license    : GPL-2.0
component  : system.utils
summary    : GTK application to configure gaming mice.
description: |
    GTK application to configure gaming mice.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(liblur)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
rundeps    :
    - libratbag
    - python3-gobject
    - python-evdev
    - python-lxml
setup      : |
    %patch -p1 < $pkgfiles/0001-ResolutionsRow-snap-to-nearest-allowed-resolution-va.patch
    %patch -p1 < $pkgfiles/0002-MouseMap-if-the-old-highlight-is-None-don-t-try-to-r.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
